data_dim: 5
n_segments: 40
n_layers: [2, 4]
n_obs_per_seg: [100, 200, 500, 1000, 2000]
data_seed: 1

ivae:
  max_iter: 70000
  lr: 000.1
  cuda: False

icebeem:
  lr_flow: 00000.1
  lr_ebm: 0.0003
  n_layers_flow: 10
  ebm_hidden_size: 32